NEWS_LATEST_ARTICLE_NUMBER = 3
NEWS_HOMEPAGE_GRID_ARTICLES_NUMBER = 4
NEWS_HOMEPAGE_LIST_ARTICLES_NUMBER = 6
NEWS_CATEGORY_PAGINATION_NUMBER = 5
NEWS_RECENT_ARTICLE_NUMBER = 3
NEWS_HOMEPAGE_SPECIAL_ARTICLES_NUMBER = 5



