# Generated by Django 5.0 on 2024-10-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_homepage', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('pending', 'Pending')], default='Draft', max_length=15)),
                ('layout', models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='List', max_length=15)),
            ],
        ),
    ]
