# Generated by Django 5.0.8 on 2024-10-26 16:09

import django.db.models.deletion
import myadmin.helpers
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='layout',
            field=models.CharField(choices=[('list', 'List'), ('grid', 'Grid')], default='list', max_length=15),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('pending', 'Pending')], default='draft', max_length=15),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('pending', 'Pending')], default='draft', max_length=15)),
                ('ordering', models.IntegerField(default=0)),
                ('special', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField()),
                ('content', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to=myadmin.helpers.get_file_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.category')),
            ],
        ),
    ]
