# Generated by Django 5.0.8 on 2024-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_alter_category_layout_alter_category_status_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='list', max_length=15),
        ),
    ]
