# Generated by Django 5.0.8 on 2024-11-12 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_article_is_homepage_alter_article_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('contacted', 'Contacted'), ('not contacted yet', 'Not contacted yet')], default='draft', max_length=17)),
                ('message', models.CharField(max_length=500)),
                ('admin_message', models.TextField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='layout',
            field=models.CharField(choices=[('list', 'List'), ('grid', 'Grid')], default='list', max_length=15),
        ),
    ]
