# Generated by Django 5.0.8 on 2024-11-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_tag_alter_contact_phone_alter_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='list', max_length=15),
        ),
    ]
