# Generated by Django 5.0.8 on 2024-11-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_article_tag_alter_category_layout_alter_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tag',
            new_name='tags',
        ),
    ]
