# Generated by Django 5.0.8 on 2024-11-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_rename_tag_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='list', max_length=15),
        ),
    ]
